// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh40iLt1xmnQngwn0_rCsPFAHW8DURya4',
    appId: '1:679079560052:web:3aebf7a0e4800986d1a221',
    messagingSenderId: '679079560052',
    projectId: 'to-do-app-66496',
    authDomain: 'to-do-app-66496.firebaseapp.com',
    storageBucket: 'to-do-app-66496.firebasestorage.app',
    measurementId: 'G-HTFNQGX53E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfgOw8Ym_g-o8pEF00i-P7YJIkWmFOz08',
    appId: '1:679079560052:android:262a1dbbac1142bdd1a221',
    messagingSenderId: '679079560052',
    projectId: 'to-do-app-66496',
    storageBucket: 'to-do-app-66496.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6I_2bzpXl08bf5rFAL6dJS4IaWRLHpKM',
    appId: '1:679079560052:ios:9ec69367265025d7d1a221',
    messagingSenderId: '679079560052',
    projectId: 'to-do-app-66496',
    storageBucket: 'to-do-app-66496.firebasestorage.app',
    iosBundleId: 'com.taskflow.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6I_2bzpXl08bf5rFAL6dJS4IaWRLHpKM',
    appId: '1:679079560052:ios:9ec69367265025d7d1a221',
    messagingSenderId: '679079560052',
    projectId: 'to-do-app-66496',
    storageBucket: 'to-do-app-66496.firebasestorage.app',
    iosBundleId: 'com.taskflow.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh40iLt1xmnQngwn0_rCsPFAHW8DURya4',
    appId: '1:679079560052:web:f460b839977b8d55d1a221',
    messagingSenderId: '679079560052',
    projectId: 'to-do-app-66496',
    authDomain: 'to-do-app-66496.firebaseapp.com',
    storageBucket: 'to-do-app-66496.firebasestorage.app',
    measurementId: 'G-CCTN8R3KM5',
  );
}
